name: digital-docket
favicon: null
layout_spectrum: 0.98115
typography_spectrum: 0.64376
title: The Digital Docket of Elliot Jarbe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73491601-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#f5bf25'
    - '#4b4455'
    - '#000000'
    - '#828282'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
