name: digital-docket
favicon: null
layout_spectrum: 0.98115
typography_spectrum: 0.64376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b0100'
    - '#ffcd54'
    - '#fffeff'
    - '#c1703d'
    - '#834746'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
